### ISSUE TITLE
群组内怎么使用机器人啊

### ISSUE THREAD

**Issue by monster1237** [finalpi/wechat2tg#11]
目前只有绑定群组之后机器人才能在群组发消息，我如果在电报群里发送消息又会直接发送至微信群里面，我想要电报群里面可以设置只接收消息不发送消息的功能，希望作者可以修复它

**Comment by finalpi** [comment]
如果你只想要在群组内接受消息而不想转发你在群组发送的消息,你可以试着取消bot的管理员权限,然后在botfather中开启隐私模式
