### ISSUE TITLE
能否支持消息免打扰？

### ISSUE THREAD

**Issue by lyrnya** [finalpi/wechat2tg#15]
开启免打扰的群，会将所有消息进行转发，能否只接收@所有人或者@自己的消息

**Comment by areidx** [comment]
当前无法获取群通知状态。控制转发可以使用黑名单白名单模式。/setting 命令。默认是黑名单模式，加入后的消息不会转发。

**Comment by lyrnya** [comment]
> 当前无法获取群通知状态。控制转发可以使用黑名单白名单模式。/setting 命令。默认是黑名单模式，加入后的消息不会转发。

那是否能实现这样的功能。
使某个群（开关控制）中带有关键字（可自行设置）的群消息进行转发

**Comment by finalpi** [comment]
v1.0.4版本会转发提到自己的微信消息,包括@自己或者@所有人的消息

**Comment by areidx** [comment]
> > 当前无法获取群通知状态。控制转发可以使用黑名单白名单模式。/setting 命令。默认是黑名单模式，加入后的消息不会转发。
> 
> 那是否能实现这样的功能。 使某个群（开关控制）中带有关键字（可自行设置）的群消息进行转发

目前不打算实现这种我感觉不太常用的功能，一般的IM软件也都是统一静音吧
