### ISSUE TITLE
请求支持多个订阅号绑定一个群组

### ISSUE THREAD

**Issue by nonlog** [finalpi/wechat2tg#16]

**Comment by areidx** [comment]
很好的提议，后续会考虑增加

**Comment by areidx** [comment]
> @areidx 还有一个小提议: 是否可以自动设置群组的名称时只设置 wx备注或者像 efb-wechat 一样设置为 <💬👤 + wx备注>, 不添加 [昵称]

dev分支加上了自己可以配置格式

**Comment by areidx** [comment]
> > > @areidx 还有一个小提议: 是否可以自动设置群组的名称时只设置 wx备注或者像 efb-wechat 一样设置为 <💬👤 + wx备注>, 不添加 [昵称]
> > 
> > 
> > dev分支加上了自己可以配置格式
> 
> 感谢，希望能再考虑一下这个小提议：当绑定群组后直接发送消息内容，而不是 "👤[备注]<昵称>：消息内容"

目前是环境变量里面自己设置的

```ts
# 消息格式配置:(#[alias]:联系人备注,#[name]:联系人昵称,#[topic]:群聊昵称,#[alias_first]:备注优先,如果没有备注就显示联系人的昵称)
## 群消息格式
ROOM_MESSAGE='<i>#[topic]</i> ---- <b>#[alias_first]: </b>'
## 公众号消息格式
OFFICIAL_MESSAGE='<b>📣#[name]: </b>'
## 联系人消息格式
CONTACT_MESSAGE='<b>#[alias_first]: </b>'
## 群消息格式(群组下)
ROOM_MESSAGE_GROUP='<b>#[alias_first]: </b>'
## 公众号消息格式(群组下)
OFFICIAL_MESSAGE_GROUP='<b>📣#[name]: </b>'
## 联系人消息格式(群组下)
CONTACT_MESSAGE_GROUP='<b>#[alias_first]: </b>'
```

**Comment by areidx** [comment]
> 很好的提议，后续会考虑增加

因为现有的功能逻辑，已经可以满足订阅号的需求。考虑到修改的成本决定不做了。

**Comment by areidx** [comment]
> > > 很好的提议，后续会考虑增加
> > 
> > 
> > 因为现有的功能逻辑，已经可以满足订阅号的需求。考虑到修改的成本决定不做了。
> 
> 请教一下如何该实现类似订阅号的功能? 是使用 bot 接收所有公众号消息吗?

需要配置API_ID和API_HASH 来登陆 telegram 自动创建对应的群组实现

**Comment by areidx** [comment]
> > > 很好的提议，后续会考虑增加
> > 
> > 
> > 因为现有的功能逻辑，已经可以满足订阅号的需求。考虑到修改的成本决定不做了。
> 
> 请教一下如何该实现类似订阅号的功能? 是使用 bot 接收所有公众号消息吗?

没有我的意思是可以接受所有的公众号消息，这个功能是存在的。请问你的需求是所有的公众号都发送到一个地方吗

**Comment by areidx** [comment]
> > > > > 很好的提议，后续会考虑增加
> > > > 
> > > > 
> > > > 因为现有的功能逻辑，已经可以满足订阅号的需求。考虑到修改的成本决定不做了。
> > > 
> > > 
> > > 请教一下如何该实现类似订阅号的功能? 是使用 bot 接收所有公众号消息吗?
> > 
> > 
> > 没有我的意思是可以接受所有的公众号消息，这个功能是存在的。请问你的需求是所有的公众号都发送到一个地方吗
> 
> 嗯嗯，算是吧，我之前用的 ehForwarderBot，因为我 tg 创建的分组，加的频道和群组有点多，使用习惯是把菜鸟，顺丰，银行提醒类的服务号放在一个群组里，那些发文章的公众号也放在一起（基本不会看🫠，也懒得取关了）

那你完全可以关闭自动转发公众号的功能，这样就不会有群组创建了
