### ISSUE TITLE
tg无法发送图片到微信

### ISSUE THREAD

**Issue by Adlyq** [finalpi/wechat2tg#17]
如题，log中没有输出，仅机器人回复发送失败

**Comment by finalpi** [comment]
请问图片的原始大小是多大,是什么格式的图片

**Comment by Adlyq** [comment]
> 请问图片的原始大小是多大,是什么格式的图片

你好，我测试用的图片是163.05k的，格式为jpg，大小1080*2400

**Comment by finalpi** [comment]
已修复，更新到最新版本试试

**Comment by Adlyq** [comment]
fixed
