### ISSUE TITLE
对本项目的一些建议

### ISSUE THREAD

**Issue by Adlyq** [finalpi/wechat2tg#18]
使用本项目一段时间了，稳定性、易用性上佳，感谢作者的付出。
同时，在使用中也有一些想法，如下，望采纳，谢谢
1. 使用发送队列，确保tg2vx的发送顺序
1. 利用tg的编辑消息功能，vx收到图片/文件等消息的时候，可以先在tg发送一个提示消息，再在文件下载好后编辑。
1. 现有的tg2vx发送成功提示有些影响体验，可以考虑以下方式
> - 利用tg已读功能，发送成功才触发已读(可能存在技术上的难度？)
> - 利用置顶和消息编辑功能，显示正在队列中的消息个数，同时可以考虑写出对应消息的链接(http.s://t.m.e/c/chatid/msgid)或者引用
> - 在登录tg后(autocg模式)，可以编辑用户的消息，在消息尾部加上(✅ or ✔)，但是此方法在文件、图片和**转发的消息**上存在问题

**Comment by areidx** [comment]
感谢你的反馈  
目前针对你提出的几点我先回复下  
1. 经过我初步对web微信行为分析,目前web微信对 _文件_ 消息之类的收发和其他客户端不太一样,需要等待全部全部文件上传完毕才发送,所以除去 _文件_ 以外的消息才能实现按照发送的顺序发送. 可以考虑实现这点
2. 可以实现
3. 打算在成功发送后编辑发送的消息,加上 ✅ or ✔ 提示

**Comment by Adlyq** [comment]
另外，建议在群组模式下，回复的消息可以在微信同样使用回复(在微信叫引用)

**Comment by areidx** [comment]
> 另外，建议在群组模式下，回复的消息可以在微信同样使用回复(在微信叫引用)

目前web微信无法引用

**Comment by areidx** [comment]
在v1.1.0完成了
