### ISSUE TITLE
网页版微信被封之后就没法登陆了

### ISSUE THREAD

**Issue by jarvie-mei** [finalpi/wechat2tg#23]
如题。

**Comment by Nimbly8836** [comment]
限制扫码吗?  README 写了这个情况 `在最近 2024-07-12 左右，部分用户使用多开或者分身登陆的微信被限制包括但不限扫码加群等功能`

**Comment by jarvie-mei** [comment]
> 限制扫码吗?  README 写了这个情况 `在最近 2024-07-12 左右，部分用户使用多开或者分身登陆的微信被限制包括但不限扫码加群等功能`

程序生成的二维码，用手机微信扫码之后登不上去。我怀疑是网页版微信无法登陆导致的。之前网页版微信能正常登陆，微信转发到tg就能用。现在我登不上网页版微信了，这个就用不了了。

**Comment by Nimbly8836** [comment]
> > 限制扫码吗?  README 写了这个情况 `在最近 2024-07-12 左右，部分用户使用多开或者分身登陆的微信被限制包括但不限扫码加群等功能`
> 
> 程序生成的二维码，用手机微信扫码之后登不上去。我怀疑是网页版微信无法登陆导致的。之前网页版微信能正常登陆，微信转发到tg就能用。现在我登不上网页版微信了，这个就用不了了。

使用的是网页协议添加了UOS登陆的请求头, 你可以使用UOS插件尝试登陆网页微信来确定. [地址](https://github.com/lqzhgood/wechat-need-web)

**Comment by jarvie-mei** [comment]
> > > 限制扫码吗?  README 写了这个情况 `在最近 2024-07-12 左右，部分用户使用多开或者分身登陆的微信被限制包括但不限扫码加群等功能`
> 
> > 
> 
> > 程序生成的二维码，用手机微信扫码之后登不上去。我怀疑是网页版微信无法登陆导致的。之前网页版微信能正常登陆，微信转发到tg就能用。现在我登不上网页版微信了，这个就用不了了。
> 
> 
> 
> 使用的是网页协议添加了UOS登陆的请求头, 你可以使用UOS插件尝试登陆网页微信来确定. [地址](https://github.com/lqzhgood/wechat-need-web)

已成功登陆。
前几天突然用不了，log也没有显示什么异常，原因未知，可能是个例。
感谢！
