### ISSUE TITLE
微信群里的企业微信号发的消息收不到. tg上的自定义表情转发到微信上全糊了.

### ISSUE THREAD

**Issue by 619dev** [finalpi/wechat2tg#24]
如题.
感谢大佬的开发.

**Comment by finalpi** [comment]
企业微信消息目前无法接收,貌似是因为web微信协议不支持接收企业微信消息.自定义表情是webm格式还是tgs格式的表情

**Comment by 619dev** [comment]
就是tg的sticker表情包.

**Comment by 619dev** [comment]
有没有办法使用ipad端登录,这样子macos上的微信客户端还能照常使用. 企业微信的消息收不到挺影响工作的.

**Comment by 619dev** [comment]
1.1.3 刚部署上线, tg表情发到微信还是糊的. 是不是web微信的限制啊

**Comment by finalpi** [comment]
@619dev web微信限制只能发1mb以内的gif，所以如果你的表情太大会被压缩到1mb以内

**Comment by Nimbly8836** [comment]
> 又搭建好了,最新版本. tg表情还是糊的. https://mjj.today/i/jL99OM https://mjj.today/i/jL9TbH https://mjj.today/i/jL9ay9

你可以提供下原始表情的链接，有空可以优化下

**Comment by 619dev** [comment]
https://t.me/addstickers/ongeki

**Comment by finalpi** [comment]
@619dev 该问题已解决,更新v1.1.9版本,并删除掉表情的缓存文件夹save-files中的文件(如果你挂载了该目录)

**Comment by 619dev** [comment]
亲测,已解决
