### ISSUE TITLE
收到的图片能不能和在微信收到的一样，以图片的形式显示，而不是以文件的形式？

### ISSUE THREAD

**Issue by chengqdevil** [finalpi/wechat2tg#25]

**Comment by finalpi** [comment]
使用 `/settings` 命令开启 `媒体质量压缩` 就会以图片的方式显示

**Comment by chengqdevil** [comment]
> 使用 `/settings` 命令开启 `媒体质量压缩` 就会以图片的方式显示

确实是可以了，虽然看着比微信上看到的还模糊，但是至少界面上好看些
