### ISSUE TITLE
基于V1.1.4，使用下来发现的几个问题，看是否能继续优化。

### ISSUE THREAD

**Issue by chengqdevil** [finalpi/wechat2tg#27]
1. tg上发送表情或者文件（发送的消息或者文件，均是tg上接收到的），会提示 `发送失败, 保存原始文件失败` ，logs日志如下：
```
2024/08/09 17:02:31,stderr,}

2024/08/09 17:02:31,stderr,  code: 'ERR_INVALID_ARG_TYPE'

2024/08/09 17:02:31,stderr,    at async FileUtils.downloadWithProxy (/app/dist/utils/FileUtils.js:66:30) {

2024/08/09 17:02:31,stderr,    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

2024/08/09 17:02:31,stderr,    at Axios.request (/app/node_modules/axios/dist/node/axios.cjs:4262:41)

2024/08/09 17:02:31,stderr,    at Axios._request (/app/node_modules/axios/dist/node/axios.cjs:4390:33)

2024/08/09 17:02:31,stderr,    at Axios.dispatchRequest (/app/node_modules/axios/dist/node/axios.cjs:4110:10)

2024/08/09 17:02:31,stderr,    at http (/app/node_modules/axios/dist/node/axios.cjs:2704:10)

2024/08/09 17:02:31,stderr,    at wrapAsync (/app/node_modules/axios/dist/node/axios.cjs:2666:10)

2024/08/09 17:02:31,stderr,    at new Promise (<anonymous>)

2024/08/09 17:02:31,stderr,    at /app/node_modules/axios/dist/node/axios.cjs:2686:5

2024/08/09 17:02:31,stderr,    at dispatchHttpRequest (/app/node_modules/axios/dist/node/axios.cjs:2964:7)

2024/08/09 17:02:31,stderr,    at setProxy (/app/node_modules/axios/dist/node/axios.cjs:2637:10)

2024/08/09 17:02:31,stderr,    at Function.from (node:buffer:325:9)

2024/08/09 17:02:31,stderr,    at new NodeError (node:internal/errors:405:5)

2024/08/09 17:02:31,stderr,"下载文件失败: TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received an instance of Object
```
2. 无论 `接受自己在微信发送的消息`是否打开，微信群的消息均会转发到对应群组。
3.  `接收公众号消息` ，如果一次存在多篇文章，只会接收到第一条文章的链接。
4. 微信群内会存在 `备注` 、 `群昵称` 、 `微信昵称` 的情况，目前在tg上有备注的情况下会显示 `（备注）微信昵称`，无备注但是有群昵称的情况，只会显示微信昵称，是否可显示 `（群昵称）微信昵称`。

**Comment by chengqdevil** [comment]
![Uploading IMG_6680.jpeg…]()
爱范儿推送了两篇文章，bot只有第一篇文章的链接

**Comment by chengqdevil** [comment]
![Uploading IMG_6680.jpeg…]()

**Comment by chengqdevil** [comment]
emmmm……不会上传截图，大概就是公众号有时候会一次性推送两篇文章，需要分别点进去查看，bot只推送第一篇文章的链接。

**Comment by Nimbly8836** [comment]
可以上传到这里 https://imgur.com/ 或者直接粘贴图片

**Comment by chengqdevil** [comment]
https://i.imgur.com/lrtRhnA.jpeg 
  https://i.imgur.com/SjrVKFP.jpeg

**Comment by finalpi** [comment]
关于第4点,可以自行配置消息模板的格式,参考:[自定义消息模板](https://github.com/finalpi/wechat2tg/blob/master/README_zh.md#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%B6%88%E6%81%AF%E6%A8%A1%E6%9D%BF)

**Comment by chengqdevil** [comment]
不知道是不是我哪里设置有问题啊，第一个问题我这边还是没解决，但是看issue其他人是正常的？我的是在nas上部署的，连接了旁路由的代理，tg接受消息、文件、表情都可以，也可以发送文字消息，但文件、图片就是发送失败。

**Comment by Nimbly8836** [comment]
> 不知道是不是我哪里设置有问题啊，第一个问题我这边还是没解决，但是看issue其他人是正常的？我的是在nas上部署的，连接了旁路由的代理，tg接受消息、文件、表情都可以，也可以发送文字消息，但文件、图片就是发送失败。

你可以提供下你设置在 docker-compose/docker run 的代理设置吗

**Comment by chengqdevil** [comment]
> > 不知道是不是我哪里设置有问题啊，第一个问题我这边还是没解决，但是看issue其他人是正常的？我的是在nas上部署的，连接了旁路由的代理，tg接受消息、文件、表情都可以，也可以发送文字消息，但文件、图片就是发送失败。
> 
> 你可以提供下你设置在 docker-compose/docker run 的代理设置吗

部署在本地另一台设备上的shellcrash
```
PROXY _HOST: '192.168.2.111'
PROXY_PORT: 17890，
# 代理类型：socks5,http,https
PROXY_PROTOCOL: 'http'
```

**Comment by chengqdevil** [comment]
部署在本地另一台设备上的shellcrash
```
PROXY _HOST: '192.168.2.111'
PROXY_PORT: '7890'
# 代理类型：socks5,http,https
PROXY_PROTOCOL: 'http'
```

**Comment by Nimbly8836** [comment]
> > > 不知道是不是我哪里设置有问题啊，第一个问题我这边还是没解决，但是看issue其他人是正常的？我的是在nas上部署的，连接了旁路由的代理，tg接受消息、文件、表情都可以，也可以发送文字消息，但文件、图片就是发送失败。
> > 
> > 
> > 你可以提供下你设置在 docker-compose/docker run 的代理设置吗
> 
> 部署在本地另一台设备上的shellcrash
> 
> ```
> PROXY _HOST: '192.168.2.111'
> PROXY_PORT: '7890'
> # 代理类型：socks5,http,https
> PROXY_PROTOCOL: 'http'
> ```

http 代理的问题, v1.2.0 已经修复

**Comment by chengqdevil** [comment]
> > > > 不知道是不是我哪里设置有问题啊，第一个问题我这边还是没解决，但是看issue其他人是正常的？我的是在nas上部署的，连接了旁路由的代理，tg接受消息、文件、表情都可以，也可以发送文字消息，但文件、图片就是发送失败。
> > > 
> > > 
> > > 你可以提供下你设置在 docker-compose/docker run 的代理设置吗
> > 
> > 
> > 部署在本地另一台设备上的shellcrash
> > ```
> > PROXY _HOST: '192.168.2.111'
> > PROXY_PORT: '7890'
> > # 代理类型：socks5,http,https
> > PROXY_PROTOCOL: 'http'
> > ```
> 
> http 代理的问题, v1.2.0 已经修复

亲测可以了，赞赞赞
