### ISSUE TITLE
群组消息是否可以支持只转发特定的人的消息？以及同一个群组转发(绑定)到多个tg群组

### ISSUE THREAD

**Issue by souvenp** [finalpi/wechat2tg#30]
只转发选定的人发送的消息
目前似乎只能绑定一个，我想对某个微信群组绑定tg群组A部分消息转发，另外再绑定tg群组B全部消息转发🤣不知道有没有人和我一样需要这种

**Comment by Nimbly8836** [comment]
这种情况太复杂了，暂时不考虑增加。
