### ISSUE TITLE
关于在tg上发送的消息转发到微信

### ISSUE THREAD

**Issue by souvenp** [finalpi/wechat2tg#31]
1.如果群组内不止一个机器人，比如发送/xxx或者@xx，也会转发到微信，是否可以增加判断特殊开头不转发？
2.现在是设置成管理员或者关闭隐私模式才会转发消息到微信，是否可以增加一个指令比如/send xx转发到微信？可能群组内聊天会有普通内容或者误发，因此不会设成管理员，但偶尔可能会要转发到微信
3.红包消息现在无法转发？

**Comment by Nimbly8836** [comment]
打算增加命令  /gs 切换当前群组是否转发自己的消息
