### ISSUE TITLE
（功能请求）屏蔽微信中已经免打扰联系人和群组

### ISSUE THREAD

**Issue by Maxwellads** [finalpi/wechat2tg#34]
当前版本会推送所有微信联系人和群组的消息。即便在微信中设置免打扰，Bot还是会推送，导致消息较为杂乱。

**Comment by Adlyq** [comment]
在tg中可以设置每个群的通知方式的，当然，可以自动根据微信的设置调整也更好。但是不知道网页版有没有提供通知方式信息

**Comment by Maxwellads** [comment]
> 在tg中可以设置每个群的通知方式的，当然，可以自动根据微信的设置调整也更好。但是不知道网页版有没有提供通知方式信息
求教，要如何设置？
另外，现在这个项目貌似是基于UOS的微信（而不是网页版）的吧

**Comment by Adlyq** [comment]
tg群组，右上角三个点，静音，自定义
注:我用的nagram

**Comment by Maxwellads** [comment]
> 在tg中可以设置每个群的通知方式的，当然，可以自动根据微信的设置调整也更好。但是不知道网页版有没有提供通知方式信息



> tg群组，右上角三个点，静音，自定义 注:我用的nagram

谢谢，我是一直用Bot看消息，所以没办法自定义

**Comment by finalpi** [comment]
@Maxwellads 可以设置群消息黑名单,/setting将群组加入进黑名单,此时消息就不会被推送了,目前只支持微信群消息

**Comment by Maxwellads** [comment]
> @Maxwellads 可以设置群消息黑名单,/setting将群组加入进黑名单,此时消息就不会被推送了,目前只支持微信群消息

找到了，感谢。还有一个办法就是用微信的Minimize Group（折叠群组），但希望未来能支持根据群组设置来自动设定黑名单！
