### ISSUE TITLE
功能许愿-tg编辑=微信撤回重发

### ISSUE THREAD

**Issue by Adlyq** [finalpi/wechat2tg#35]
如题，编辑tg消息则撤回微信相应消息并重新发送编辑后消息

**Comment by Adlyq** [comment]
另外，目前接收不到其他人转发的视频号消息

**Comment by Nimbly8836** [comment]
> 如题，编辑tg消息则撤回微信相应消息并重新发送编辑后消息

逻辑不一样微信本来就没编辑功能，而且现在已经实现了删除消息会撤回（2分钟内的消息）。
