### ISSUE TITLE
[BUG] 不能自动创建文件夹

### ISSUE THREAD

**Issue by LittleChest** [finalpi/wechat2tg#42]
https://github.com/finalpi/wechat2tg/issues/42#issuecomment-2365272695

**Comment by Nimbly8836** [comment]
现在是有这个功能的，会自动创建一个名为 WeChat 文件夹。自动创建的群聊都会放在这个文件夹下面。
如果你没创建文件夹的话我目前想的情况是：
1. 非 Telegram Premium 用户只能创建10个文件夹，创建的时候出错了。
2. 创建文件夹发生了未知错误

如果创建文件夹出错了应该会有日志。

**Comment by LittleChest** [comment]
> 现在是有这个功能的，会自动创建一个名为 WeChat 文件夹。自动创建的群聊都会放在这个文件夹下面。 如果你没创建文件夹的话我目前想的情况是：
> 
> 1. 非 Telegram Premium 用户只能创建10个文件夹，创建的时候超过了这个限制出错了
> 2. 创建文件夹发生了未知错误
> 
> 如果创建文件夹出错了应该会有日志。

原来tg还有文件夹数量限制 ~~杜鼠鼠想钱想疯了~~

**Comment by LittleChest** [comment]
![Screenshot_20240922-020449_Nekogram](https://github.com/user-attachments/assets/8df45563-7193-456a-88aa-d28a0da8c920)
hmm并没有创建 而且后台也没有什么报错 唯一可疑的只有
```
uncaughtException TypeError: Cannot read properties of undefined (reading 'id')
    at SetupServiceImpl.addToFolder (/app/dist/service/impl/SetupServiceImpl.js:89:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async TelegramUserClient.createGroup (/app/dist/client/TelegramUserClient.js:158:13)
    at async WeChatClient.message (/app/dist/client/WechatClient.js:590:32)
```

**Comment by Nimbly8836** [comment]
> ```
> uncaughtException TypeError: Cannot read properties of undefined (reading 'id')
>     at SetupServiceImpl.addToFolder (/app/dist/service/impl/SetupServiceImpl.js:89:33)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async TelegramUserClient.createGroup (/app/dist/client/TelegramUserClient.js:158:13)
>     at async WeChatClient.message (/app/dist/client/WechatClient.js:590:32)
> ```

是的这是一个 bug，当前如果被这个问题困扰可以手动创建一个名为 WeChat 的文件夹。
后续会修复这个问题的。
