### ISSUE TITLE
[建议]能否接入chatgpt/其他大模型api

### ISSUE THREAD

**Issue by kurobaryo** [finalpi/wechat2tg#44]
能否接入chatgpt或其他大模型api? 或者允许群组里除管理员外的其他bot发的消息能够被转发到微信，这样就不需要额外配置

**Comment by Nimbly8836** [comment]
> 能否接入chatgpt或其他大模型api?  

由于看到其他使用类似的协议的仓库反馈——怀疑是接入了 GPT/AI 导致的规模封号，不考虑增加风险。  

> 或者允许群组里除管理员外的其他bot发的消息能够被转发到微信  

这个可以考虑

**Comment by kurobaryo** [comment]
嗯嗯，第二个方法可能实现起来更加简单点，并且拓展性会高很多

**Comment by Nimbly8836** [comment]
v1.3.2 已经实现
