### ISSUE TITLE
Tg发送到微信的文件名中的空格、短横线“-”会被替换成下划线“_”。

### ISSUE THREAD

**Issue by chengqdevil** [finalpi/wechat2tg#46]
Tg发送到微信的文件名中的空格、短横线“-”会被替换成下划线“_”。
而在微信发送的文件，在tg中正常显示。

**Comment by Nimbly8836** [comment]
简单的测试了一下文本文件，文件名带有 空格 和 - 都没被替换。
不知道能不能提供你的文件名称。

**Comment by chengqdevil** [comment]
> 简单的测试了一下文本文件，文件名带有 空格 和 - 都没被替换。 不知道能不能提供你的文件名称。

短的文件名好像不会，比如“我们是共产主义接班人-20241031.docx”
长的就会，比如“福州市轨道交通各类系统接入技术规程-集团意见2024101502.docx”

**Comment by Nimbly8836** [comment]
这是 TG 自己的问题，暂时无法修改。
