### ISSUE TITLE
errno: 11数据库损坏，查询群组绑定正常，但是接收不到消息，发出的消息会发错人活着微信群

### ISSUE THREAD

**Issue by chengqdevil** [finalpi/wechat2tg#47]
`
2024/10/24 08:37:21 | stdout | code: 'SQLITE_CORRUPT'
2024/10/24 08:37:21 | stdout | errno: 11,
2024/10/24 08:37:21 | stdout | uncaughtException [Error: SQLITE_CORRUPT: database disk image is malformed] {
2024/10/24 08:32:43 | stdout | }
`

**Comment by Nimbly8836** [comment]
因为转发到哪里是依赖数据库的。请尝试挂载其他路径或者用新的数据库文件。

**Comment by chengqdevil** [comment]
> 因为转发到哪里是依赖数据库的。请尝试挂载其他路径或者用新的数据库文件。

挂载其他路径或者用新的数据库文件，是不是又得重新绑定了

**Comment by chengqdevil** [comment]
> > > 因为转发到哪里是依赖数据库的。请尝试挂载其他路径或者用新的数据库文件。
> > 
> > 
> > 挂载其他路径或者用新的数据库文件，是不是又得重新绑定了
> 
> 是的，没办法 除非你修复旧的文件

解决了，用sqlite客户端导出sql文件，再从sql文件导入到数据库，替换新的数据库就好了。
