### ISSUE TITLE
手动绑定群组失败

### ISSUE THREAD

**Issue by chengqdevil** [finalpi/wechat2tg#48]
当前最新版本，机器人的隐私模式已关闭，手动绑定群组后，使用bind命令仍提示未绑定

**Comment by finalpi** [comment]
未复现该问题,请确认项目有挂载目录的数据库的修改权限,绑定的时候日志是否有错误信息

**Comment by chengqdevil** [comment]
> 未复现该问题,请确认项目有挂载目录的数据库的修改权限,绑定的时候日志是否有错误信息
好像是代理不稳定导致的，换个代理就好了
