### ISSUE TITLE
开始媒体质量压缩后，部分照片旋转了90度

### ISSUE THREAD

**Issue by hououinkami** [finalpi/wechat2tg#49]
使用的是最新版镜像，媒体质量压缩选项为开启，收到的照片中，部分高>宽的竖照片会被横过来，顺时针90度或逆时针90度均有，请问是压缩过程中出现的bug吗？谢谢

**Comment by finalpi** [comment]
未复现该问题,是部分照片才会出现吗,我发了两张3072*4080和4080*3072的照片都是正常显示,你能提供下出现问题照片的分辨率吗

**Comment by hououinkami** [comment]
我看了最近几张被旋转的照片，均为900*1200

**Comment by hououinkami** [comment]
> 未复现该问题,是部分照片才会出现吗,我发了两张`3072x4080`和`4080x3072`的照片都是正常显示,你能提供下出现问题照片的分辨率吗

我看了最近几张被旋转的照片，均为900*1200

**Comment by finalpi** [comment]
我制作了一张`900x1200`的图片仍然未复现这个问题

![](https://s1.imagehub.cc/images/2024/11/08/1897b41cb1b05e1b2009d90c5cdac74b.jpg)

**Comment by finalpi** [comment]
你可以试试用照片涂抹工具,将照片中所有元素都涂抹掉,然后尝试发送这张涂抹后的照片,如果发送出现旋转90度的问题,可以把这张照片上传到github,如果你不想暴露地址和拍摄设备的信息,别忘记删除掉图片的元数据

**Comment by hououinkami** [comment]
我在网上找到了一张照片，发送之后被旋转了！
![Uploading dfdb2483567b4f03b8523d445233c6f1.jpg…]()

**Comment by finalpi** [comment]
感谢你的反馈,的确会有这个问题,原因是相机元数据带上了旋转信息,这个问题将在下一次发行中被修复

**Comment by hououinkami** [comment]
感谢！
