### ISSUE TITLE
（功能请求）消息中用户名不换行

### ISSUE THREAD

**Issue by u2x1** [finalpi/wechat2tg#51]
如图，不换行的文本消息导致用户名和消息文本争夺视觉焦点，显得比较杂乱。希望可以在处理消息时默认不换行，用户需要时自行在环境变量里加 '\n'。

<details>
<summary>不换行</summary>

> ![image](https://github.com/user-attachments/assets/da345174-7dc6-447a-b91b-ed2e8660e7f4)

</details>
<details>
<summary>换行</summary>

> ![image](https://github.com/user-attachments/assets/5a415429-d49c-4b60-9425-91d0661ab874)
</details>

https://github.com/finalpi/wechat2tg/blob/a0467b8cfff412df60f266ecd40ace5c343079c8/src/model/Message.ts#L41

**Comment by finalpi** [comment]
在 [v1.2.9](https://github.com/finalpi/wechat2tg?tab=readme-ov-file#docker-compose-recommended) 版本中添加了新的环境变量可以自定义用户的身份和消息体内容显示的样式
`MESSAGE_DISPLAY: '#[identity]#[br]#[body]'`
