### ISSUE TITLE
wx2tg启动报错

### ISSUE THREAD

**Issue by U188** [finalpi/wechat2tg#6]
![image](https://github.com/finalpi/wechat2tg/assets/54225629/d6caea94-147e-4596-a08e-881b4fa31b04)

**Comment by finalpi** [comment]
能提供一下配置信息吗

**Comment by U188** [comment]
> 能提供一下配置信息吗

是指服务器2h4g吗，使用http代理

**Comment by finalpi** [comment]
我并未复现该问题,请确认所用的协议是http,并检查你的代理配置docker run -itd --env BOT_TOKEN="" --env HOST="192.168.1.118" --env PORT="20172" --env USERNAME="" --env PASSWORD="" --env PROTOCOL="http" finalpi/wechat2tg:latest
