### ISSUE TITLE
無法執行

### ISSUE THREAD

**Issue by deg36049** [finalpi/wechat2tg#7]
node:internal/process/promises:279
triggerUncaughtException(err, true /* fromPromise */);
 ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "解析 JSON 文件失败: SyntaxError: Unexpected token } in JSON at position 39".] {
code: 'ERR_UNHANDLED_REJECTION'
}

**Comment by a106301056** [comment]
[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "解析 JSON 文件失败: SyntaxError: Unexpected non-whitespace character after JSON at position 39".] {
  code: 'ERR_UNHANDLED_REJECTION'
}

**Comment by finalpi** [comment]
最新版本已修复
