### ISSUE TITLE
请问可以对消息进行分组吗

### ISSUE THREAD

**Issue by ayanamimcy** [finalpi/wechat2tg#9]
感谢作者开发出这个工具，很好用。
我这边想提问一下可以对消息进行分组吗。现在所有的消息都在机器人的聊天框内，实在是太混乱了。

**Comment by areidx** [comment]
因为协议问题导致无法获取用户的唯一id，而且目前只用到了telegram的api。打算在后续版本增加分组功能。

**Comment by areidx** [comment]
v1.0.2 中增加了手动绑定群组功能

**Comment by liuran001** [comment]
是否考虑通过群组topic模式对对话进行分组，topic直观而且方便管理

**Comment by finalpi** [comment]
> 是否考虑通过群组topic模式对对话进行分组，topic直观而且方便管理

不错的建议,我们会在后续版本加入这个功能
